tiers = {
    "다이아몬드": [(5000, 5350), (5350, 5700), (5700, 6050), (6050, 6400)],
    "플래티넘": [(3600, 3950), (3950, 4300), (4300, 4650), (4650, 5000)],
    "골드": [(2400, 2700), (2700, 3000), (3000, 3300), (3300, 3600)],
    "실버": [(1400, 1650), (1650, 1900), (1900, 2150), (2150, 2400)],
    "브론즈": [(600, 800), (800, 1000), (1000, 1200), (1200, 1400)],
    "아이언": [(0, 150), (150, 300), (300, 450), (450, 600)],
}

char_code = {
    "Jackie": 1,
    "Aya": 2,
    "Fiora": 3,
    "Magnus": 4,
    "Zahir": 5,
    "Nadine": 6,
    "Hyunwoo": 7,
    "Hart": 8,
    "Isol": 9,
    "LiDailin": 10,
    "Yuki": 11,
    "Hyejin": 12,
    "Xiukai": 13,
    "Chiara": 14,
    "Sissela": 15,
    "Silvia": 16,
    "Adriana": 17,
    "Shoichi": 18,
    "Emma": 19,
    "Lenox": 20,
    "Rozzi": 21,
    "Luke": 22,
    "Cathy": 23,
    "Adela": 24,
    "Bernice": 25,
    "Barbara": 26,
    "Alex": 27,
    "Sua": 28,
    "Leon": 29,
    "Eleven": 30,
    "Rio": 31,
    "William": 32,
    "Nicky": 33,
    "Nathapon": 34,
    "Jan": 35,
    "Eva": 36,
    "Daniel": 37,
    "Jenny": 38,
    "Camilo": 39,
    "Chloe": 40,
    "Johann": 41,
    "Bianca": 42,
    "Celine": 43,
    "Echion": 44,
    "Mai": 45,
    "Aiden": 46,
    "Laura": 47,
    "Tia": 48,
    "Felix": 49,
    "Elena": 50,
    "Priya": 51,
    "Adina": 52,
    "Markus": 53,
    "Karla": 54,
    "Estelle": 55,
    "Piolo": 56,
    "Martina": 57,
    "Haze": 58,
    "Issac": 59,
    "Tazia": 60,
    "Irem": 61,
    "Theodore": 62,
    "Lyanh": 63,
    "Vanya": 64,
    "DebiMarlene": 65,
    "Arda": 66,
    "Abigail": 67,
    "Alonso": 68,
    "Leni": 69,
    "Tsubame": 70,
    "Kenneth": 71,
    "Katja": 72,
    "Charlotte": 73,
    "Darko": 74,
    "Lenore": 75,
    "Garnet": 76,
    "Yumin": 77,
    "Hisui": 78,
}

char_korean = {
    "Jackie": "재키",
    "Aya": "아야",
    "Hyunwoo": "현우",
    "Magnus": "매그너스",
    "Fiora": "피오라",
    "Nadine": "나딘",
    "Zahir": "자히르",
    "Hart": "하트",
    "Isol": "아이솔",
    "LiDailin": "리다이린",
    "Yuki": "유키",
    "Hyejin": "혜진",
    "Xiukai": "쇼우",
    "Sissela": "시셀라",
    "Chiara": "키아라",
    "Adriana": "아드리아나",
    "Silvia": "실비아",
    "Shoichi": "쇼이치",
    "Emma": "엠마",
    "Lenox": "레녹스",
    "Rozzi": "로지",
    "Luke": "루크",
    "Cathy": "캐시",
    "Adela": "아델라",
    "Bernice": "버니스",
    "Barbara": "바바라",
    "Alex": "알렉스",
    "Sua": "수아",
    "Leon": "레온",
    "Eleven": "일레븐",
    "Rio": "리오",
    "William": "윌리엄",
    "Nicky": "니키",
    "Nathapon": "나타폰",
    "Jan": "얀",
    "Eva": "이바",
    "Daniel": "다니엘",
    "Jenny": "제니",
    "Camilo": "카밀로",
    "Chloe": "클로에",
    "Johann": "요한",
    "Bianca": "비앙카",
    "Celine": "셀린",
    "Echion": "에키온",
    "Mai": "마이",
    "Aiden": "에이든",
    "Laura": "라우라",
    "Tia": "띠아",
    "Felix": "펠릭스",
    "Elena": "엘레나",
    "Priya": "프리야",
    "Adina": "아디나",
    "Markus": "마커스",
    "Karla": "칼라",
    "Estelle": "에스텔",
    "Piolo": "피올로",
    "Martina": "마르티나",
    "Haze": "헤이즈",
    "Issac": "아이작",
    "Tazia": "타지아",
    "Irem": "이렘",
    "Theodore": "테오도르",
    "Lyanh": "이안",
    "Vanya": "바냐",
    "DebiMarlene": "데비마를렌",
    "Arda": "아르다",
    "Abigail": "아비게일",
    "Alonso": "알론소",
    "Leni": "레니",
    "Tsubame": "츠바메",
    "Kenneth": "케네스",
    "Katja": "카티야",
    "Charlotte": "샬럿",
    "Darko": "다르코",
    "Lenore": "르노어",
    "Garnet": "가넷",
    "Yumin": "유민",
    "Hisui": "히스이",
}

char_english = {
    "재키": "Jackie",
    "아야": "Aya",
    "현우": "Hyunwoo",
    "매그너스": "Magnus",
    "피오라": "Fiora",
    "나딘": "Nadine",
    "자히르": "Zahir",
    "하트": "Hart",
    "아이솔": "Isol",
    "리다이린": "LiDailin",
    "유키": "Yuki",
    "혜진": "Hyejin",
    "쇼우": "Xiukai",
    "시셀라": "Sissela",
    "키아라": "Chiara",
    "아드리아나": "Adriana",
    "실비아": "Silvia",
    "쇼이치": "Shoichi",
    "엠마": "Emma",
    "레녹스": "Lenox",
    "로지": "Rozzi",
    "루크": "Luke",
    "캐시": "Cathy",
    "아델라": "Adela",
    "버니스": "Bernice",
    "바바라": "Barbara",
    "알렉스": "Alex",
    "수아": "Sua",
    "레온": "Leon",
    "일레븐": "Eleven",
    "리오": "Rio",
    "윌리엄": "William",
    "니키": "Nicky",
    "나타폰": "Nathapon",
    "얀": "Jan",
    "이바": "Eva",
    "다니엘": "Daniel",
    "제니": "Jenny",
    "카밀로": "Camilo",
    "클로에": "Chloe",
    "요한": "Johann",
    "비앙카": "Bianca",
    "셀린": "Celine",
    "에키온": "Echion",
    "마이": "Mai",
    "에이든": "Aiden",
    "라우라": "Laura",
    "띠아": "Tia",
    "펠릭스": "Felix",
    "엘레나": "Elena",
    "프리야": "Priya",
    "아디나": "Adina",
    "마커스": "Markus",
    "칼라": "Karla",
    "에스텔": "Estelle",
    "피올로": "Piolo",
    "마르티나": "Martina",
    "헤이즈": "Haze",
    "아이작": "Issac",
    "타지아": "Tazia",
    "이렘": "Irem",
    "테오도르": "Theodore",
    "이안": "Lyanh",
    "바냐": "Vanya",
    "데비마를렌": "DebiMarlene",
    "아르다": "Arda",
    "아비게일": "Abigail",
    "알론소": "Alonso",
    "레니": "Leni",
    "츠바메": "Tsubame",
    "케네스": "Kenneth",
    "카티야": "Katja",
    "샬럿": "Charlotte",
    "다르코": "Darko",
    "르노어": "Lenore",
    "가넷": "Garnet",
    "유민": "Yumin",
    "히스이": "Hisui",
}

char_weapons = {
    "재키": ["단검", "양손검", "도끼", "쌍검"],
    "아야": ["권총", "돌격소총", "저격총"],
    "현우": ["글러브", "톤파"],
    "매그너스": ["망치", "방망이"],
    "피오라": ["레이피어", "양손검", "창"],
    "나딘": ["활", "석궁"],
    "자히르": ["투척", "암기"],
    "하트": ["기타"],
    "아이솔": ["권총", "돌격소총"],
    "리다이린": ["글러브", "쌍절곤"],
    "유키": ["양손검", "쌍검"],
    "혜진": ["활", "암기"],
    "쇼우": ["단검", "창"],
    "시셀라": ["투척", "암기"],
    "키아라": ["레이피어"],
    "아드리아나": ["투척"],
    "실비아": ["권총"],
    "쇼이치": ["단검"],
    "엠마": ["암기", "아르카나"],
    "레녹스": ["채찍"],
    "로지": ["권총"],
    "루크": ["방망이"],
    "캐시": ["단검"],
    "아델라": ["방망이", "레이피어"],
    "버니스": ["저격총"],
    "바바라": ["방망이"],
    "알렉스": ["톤파", "암기", "권총", "양손검"],
    "수아": ["방망이", "망치"],
    "레온": ["글러브", "톤파"],
    "일레븐": ["망치"],
    "리오": ["활"],
    "윌리엄": ["투척"],
    "니키": ["글러브"],
    "나타폰": ["카메라"],
    "얀": ["글러브", "톤파"],
    "이바": ["투척"],
    "다니엘": ["단검"],
    "제니": ["권총"],
    "카밀로": ["레이피어", "쌍검"],
    "클로에": ["암기"],
    "요한": ["아르카나"],
    "비앙카": ["아르카나"],
    "셀린": ["투척"],
    "에키온": ["VF의수", "vf의수"],
    "마이": ["채찍"],
    "에이든": ["양손검"],
    "라우라": ["채찍"],
    "띠아": ["방망이"],
    "펠릭스": ["창"],
    "엘레나": ["레이피어"],
    "프리야": ["기타"],
    "아디나": ["아르카나"],
    "마커스": ["도끼", "망치"],
    "칼라": ["석궁"],
    "에스텔": ["도끼"],
    "피올로": ["쌍절곤"],
    "마르티나": ["카메라"],
    "헤이즈": ["돌격소총"],
    "아이작": ["톤파"],
    "타지아": ["암기"],
    "이렘": ["투척"],
    "테오도르": ["저격총"],
    "이안": ["단검"],
    "바냐": ["아르카나"],
    "데비마를렌": ["양손검"],
    "아르다": ["아르카나"],
    "아비게일": ["도끼"],
    "알론소": ["글러브"],
    "레니": ["권총"],
    "츠바메": ["암기"],
    "케네스": ["도끼"],
    "카티야": ["저격총"],
    "샬럿": ["아르카나"],
    "다르코": ["방망이"],
    "르노어": ["기타"],
    "가넷": ["방망이"],
    "유민": ["아르카나"],
    "히스이": [],
}


weapon_korean = {
    "Glove": "글러브",
    "Tonfa": "톤파",
    "Bat": "방망이",
    "Hammer": "망치",
    "Whip": "채찍",
    "HighAngleFire": "투척",
    "DirectFire": "암기",
    "Bow": "활",
    "CrossBow": "석궁",
    "Pistol": "권총",
    "AssaultRifle": "돌격소총",
    "SniperRifle": "저격총",
    "Axe": "도끼",
    "OneHandSword": "단검",
    "TwoHandSword": "양손검",
    "DualSword": "쌍검",
    "Spear": "창",
    "Nunchaku": "쌍절곤",
    "Rapier": "레이피어",
    "Guitar": "기타",
    "Camera": "카메라",
    "Arcana": "아르카나",
    "VFArm": "VF의수",
}

weapon_english = {
    "글러브": "Glove",
    "톤파": "Tonfa",
    "방망이": "Bat",
    "망치": "Hammer",
    "채찍": "Whip",
    "투척": "HighAngleFire",
    "암기": "DirectFire",
    "활": "Bow",
    "석궁": "CrossBow",
    "권총": "Pistol",
    "돌격소총": "AssaultRifle",
    "저격총": "SniperRifle",
    "도끼": "Axe",
    "단검": "OneHandSword",
    "양손검": "TwoHandSword",
    "쌍검": "DualSword",
    "창": "Spear",
    "쌍절곤": "Nunchaku",
    "레이피어": "Rapier",
    "기타": "Guitar",
    "카메라": "Camera",
    "아르카나": "Arcana",
    "VF의수": "VFArm",
}
